FROM node:16.13.2-alpine AS BUILD_IMAGE

ARG DASHY_VERSION=2.0.3

RUN apk add git python3 make g++ && \
    git clone -b ${DASHY_VERSION} https://github.com/Lissy93/dashy.git /tmp/dashy

WORKDIR /tmp/dashy

RUN yarn install --frozen-lockfile --network-timeout 1000000

COPY ./public ./public/

RUN yarn build

FROM nginx:1.21

WORKDIR /var/www/html

COPY --from=BUILD_IMAGE /tmp/dashy/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
